# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'consonance:$(build.buildId)'

steps:
- task: Gradle@2
  inputs:
    #workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'

- task: CopyFiles@2
  inputs:
    contents: '**/consonance*.jar'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: Docker@0
  displayName: 'Build an image'
  inputs:
    azureSubscription: 'Free Trial (36667a1f-4c7f-4e5a-9c1d-5c641de0dc1f)'

    azureContainerRegistry: '{"loginServer":"sparetimecontainers.azurecr.io", "id" : "/subscriptions/36667a1f-4c7f-4e5a-9c1d-5c641de0dc1f/resourceGroups/sparetimedevs_resource_groups/providers/Microsoft.ContainerRegistry/registries/sparetimecontainers"}'

    includeLatestTag: true

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    azureSubscription: 'Free Trial (36667a1f-4c7f-4e5a-9c1d-5c641de0dc1f)'

    azureContainerRegistry: sparetimecontainers.azurecr.io

    action: 'Push an image'


