resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604
  demands: java

steps:
- task: Gradle@2
  displayName: 'gradlew build'
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'

- task: Docker@0
  displayName: 'Build an image'
  inputs:
    azureSubscription: 'Free Trial (36667a1f-4c7f-4e5a-9c1d-5c641de0dc1f)'

    azureContainerRegistry: '{"loginServer":"sparetimecontainers.azurecr.io", "id" : "/subscriptions/36667a1f-4c7f-4e5a-9c1d-5c641de0dc1f/resourceGroups/sparetimedevs_resource_groups/providers/Microsoft.ContainerRegistry/registries/sparetimecontainers"}'

    includeLatestTag: true


- task: Docker@0
  displayName: 'Push an image'
  inputs:
    azureSubscription: 'Free Trial (36667a1f-4c7f-4e5a-9c1d-5c641de0dc1f)'

    azureContainerRegistry: '{"loginServer":"sparetimecontainers.azurecr.io", "id" : "/subscriptions/36667a1f-4c7f-4e5a-9c1d-5c641de0dc1f/resourceGroups/sparetimedevs_resource_groups/providers/Microsoft.ContainerRegistry/registries/sparetimecontainers"}'

    action: 'Push an image'

    includeLatestTag: true


