version: '3.7'

services:

  mongodb:
    image: mongo:4.1.3
    container_name: con-mongo
    restart: always
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null